typedef char *(*func_ptr)(t_token *, char **, int *);

#ifndef TOKEN_FILLERS
# define TOKEN_FILLERS (func_ptr[128]){\
	end_of_line_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	commands_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	separators_token,\
	commands_token,\
	parenthesis_token,\
	parenthesis_token,\
	commands_token,\
	wrong_token,\
	wrong_token,\
	commands_token,\
	wrong_token,\
	wrong_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	wrong_token,\
	wrong_token,\
	separators_token,\
	wrong_token,\
	separators_token,\
	wrong_token,\
	wrong_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	wrong_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	commands_token,\
	wrong_token,\
	separators_token,\
	wrong_token,\
	wrong_token,\
	wrong_token\
}

#endif