typedef char *(*func_ptr)(char **, char *);

#ifndef FUNC_ARRAY
# define FUNC_ARRAY (func_ptr[128]){
	separators,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	skip_whitespaces,\
	skip_whitespaces,\
	skip_whitespaces,\
	skip_whitespaces,\
	skip_whitespaces,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	skip_whitespaces,\
	wrong_tok,\
	filtered_dup,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	separators,\
	filtered_dup,\
	parenthesis,\
	parenthesis,\
	filtered_dup,\
	wrong_tok,\
	wrong_tok,\
	filtered_dup,\
	wrong_tok,\
	wrong_tok,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	wrong_tok,\
	wrong_tok,\
	separators,\
	wrong_tok,\
	separators,\
	wrong_tok,\
	wrong_tok,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	filtered_dup,\
	wrong_tok,\
	separators,\
	wrong_tok,\
	wrong_tok,\
	wrong_tok\
}

#endif